version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    versioning-strategy: increase-if-necessary
    schedule:
      interval: daily
    labels:
      - mergewhenready
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - mergewhenready
