dist: trusty
install:
- for i in $(cat .circle-ruby) ; do rvm install $i || exit 1 ; done
- for i in $(cat .circle-ruby) ; do rvm-exec $i gem install bundler || exit 1 ; done
- for i in $(cat .circle-ruby) ; do rvm-exec $i bundle install || exit 1 ; done
script:
- for i in $(cat .circle-ruby) ; do rvm-exec $i bundle exec rake test || exit 1 ;
  done
notifications:
  email: false
  slack:
    secure: v8BhASiiYX1P5yNR/1s874dolHB9GMCJlftqk+t8QpqIvgJ4AWvQSIZg7tJlS6nRiIFSFyehLOY/JTu5/4yGpzlrVeyB+Pk4hpkvaEmstmpjVpCwdLKy58mio/80WYZx8HW889oaiJoQENpyclaEH+RGtSWP6isset/F6pQCo5BHTTou5UaM9tFkvKcJChqprLVT74/yXyx0jAgqS7y6W5gkj/TVrzfXi2JRMNWe+LQJP54U4Kmo3iyRfaEBejZH6Jhwk+gpIqfuTucBl7IjlhKRwRgUMAAqeZmr/DNtnWI5XRL2bfJkRrKAGwUKH4HUiGcZLmb1Qv6+HgkfTm3AJE2zsfpA/2N2bezK22i5YOuBY/4UPF+t+gnuh6wb2O824uaJ1Z6CMggkFgvhPT6cjIDQaWVXKEW53+YzH2DOpWHWPA9dfLFvK31B4OgTRE5Qvt0qYcNt+Vg5TYnuv89BhThRcGLi+9YMGmaEprhryKmxRWRm0Rzu4tYfRBj0QEZ3RmbehUNcitKtKRsmi3MWJblfF8HHoAatPtmYvOGohtCeZvrf1RmopWsyDTSpTscXG5oXEnQ0fT1LozzPuKBg1sxPCtgifFzZ8nmENxiT7ECoBl1EFtIJ/EvPryD7rIYzlHcgUEnxQRQpGnD0lCCfr76VCHxwX5JZSqayGksKhKw=
